### ISSUE TITLE
SNAP removal?

### ISSUE THREAD

**Issue by gr4n0t4** [SAR-ARD/s1ard#218]
Hello, I would like to know if there is intention of removing SNAP.
I've been asked this task for [ERS_NRB](https://github.com/SAR-ARD/ERS_NRB) and I would like to know if you tried or know how difficult would be. I remember having this conversation in the past.
Thank you

**Comment by johntruckenbrodt** [comment]
Hi Ricardo, the idea has been around for some time but it has not done yet.
I have not done any estimation of the effort yet. 
Progress is tracked here: https://github.com/SAR-ARD/s1ard/issues/205

I am closing this issue. Feel free to open new ones or contribute to the one above.

**Comment by gr4n0t4** [comment]
Thank you
