### ISSUE TITLE
improve log file output

### ISSUE THREAD

**Issue by johntruckenbrodt** [SAR-ARD/s1ard#88]
When recently running a larger processing example, I discovered some shortcomings with the current log file content. Some observations:
- one always has to check both the command line stdout as well as the processor log file to get a full picture of the processor run
- each log file entry prints the full list of currently processed scenes. Thsi becomes cluttered when processing a lot of scenes at once
- the time stamp in the log file name contains hour and minute. Being more precise would prevent multiple parallel processes writing into the same file. However, including the second might not be precise enough either. Perhaps a unique identifier needs to be included
- the identification of failed scenes is fairly time consuming; this is due to the very long log files in large processing runs and the insufficient info given on error

just a first list of thoughts. To be further discussed.

**Comment by maawoo** [comment]
Just stumbled upon this, which might be relevant for saving the command line stdout of SNAP: https://forum.step.esa.int/t/where-are-snap-gpt-from-cli-logfiles/39473

Is pyroSAR capturing the stdout of SNAP in any way?

**Comment by johntruckenbrodt** [comment]
Hi @maawoo currently this is not possible. the respective SNAP processing functions internally call `pyroSAR.snap.auxil.gpt` which itself calls `pyroSAR.snap.auxil.execute`. In this function the command is executed using `subprocess.Popen`, which returns `stdout` and `stderr` (because the respective variables are set to `subprocess.PIPE` in `Popen`). The most straightforward would be to directly write to a logfile inside function `execute` and pass a variable for the log file name to `gpt` and S1_NRB's SNAP processing functions. So it is considered with some effort to implement this.

**Comment by johntruckenbrodt** [comment]
Here some further thinking...  
I think it is best to entirely replace the `log_dir` configuration parameter with `logfile` so that a user can directly define where the file is written to. In case this parameter is set to `None`, all logs could just be printed to the console where they could be picked up by e.g. Slurm logging mechanisms.
